### **importado librerías**

In [1]:
import numpy as np #el np es un alias del nombre de la biblioteca numpy
import sys



In [2]:
print('hello world!')

hello world!


### creando una lista de diez elementos

In [3]:
lista1 = list(range(1, 11))
lista1


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
type(lista1)

list

###transformando una lista a un Array

In [5]:
arreglo = np.array(lista1)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### consutando el tipo de dato numerico del arreglo

In [6]:
arreglo.dtype

dtype('int64')

### creando una lista de solo numeros unos

In [7]:
unos = np.ones(10)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
ceros = np.zeros(100)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### lista de datos compuestos (transformando a Array)

In [9]:
lista2 = ['yerko', 2, 5.6, True]
lista2

['yerko', 2, 5.6, True]

### transformando la lista mixta en array

u32 hace referencia al estandar unicode

In [10]:
arreglo2 = np.array(lista2)
arreglo2

array(['yerko', '2', '5.6', 'True'], dtype='<U32')

### **consultando la cantidad de memoria ocupada por estructura (paquete Sys)**

In [11]:
memoria_lista = sys.getsizeof(lista1)
memoria_arreglo = sys.getsizeof(arreglo)

print()

### otros metodos de numpy

In [12]:
print(f'Shape:', arreglo.shape) #dimensiones
print(f'dimensiones:', arreglo.shape) #dimensiones
print(f'Shape:', arreglo.shape) #dimensiones
print(f'Shape:', arreglo.shape) #dimensiones


Shape: (10,)
dimensiones: (10,)
Shape: (10,)
Shape: (10,)


### transformando el arreglo de int a float

In [13]:
new_arreglo = arreglo.astype(float) #se puede especificar el tipo de N° flotante (float16)
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### aplicando paquete random

In [23]:
np.random.rand() #genera numeros aleatorios del rango [0, 1]

0.18823801096925852

#### generando arreglo aleatorio de numeros enteros

In [17]:
np.random.randint(1, 100, 10)

array([81, 77,  7, 41, 46, 13, 44,  2, 17, 27], dtype=int32)

#### generando una matriz aleatoria de 10 numeros enteros del 1 al 100

In [30]:
matriz2 = np.random.randint(1, 101,(10,10))
matriz2

array([[ 28,   4,  18,  88,  86,  61,  11,  51,  14,  32],
       [ 28,  39,  61,  42,  91,  42,  76,  51,  43,  13],
       [  9,  70,  29,  12,  41,  36,  77,  47,  52,  58],
       [  8,  90,  35,  44,  11,  24,  16,   3,  54,  46],
       [ 94,  28,   1,  96,  58,   8,  13,  77,  44,  58],
       [ 44,  53,   5,  55,  44,  52,  73,  27,  82,  38],
       [ 55,  60,  36,  83,   6,  56,  15,  17,  12,  57],
       [ 33,  99,  66,  47,  66,  12,  90,  93,  92,  40],
       [ 67,   7,   4,  43,  56,  83, 100,   3,  22,  49],
       [ 85,  73,  38,  79,  11,  94,  52,  94,  73,  58]], dtype=int32)